bundler_args: "--path vendor/bundle"
before_script:
  - "cp config/database.travis.yml config/database.yml"
script: "RAILS_ENV=test bundle exec rake db:drop db:create db:migrate spec"
rvm:
  - 2.0.0
  - 1.9.3
notifications:
  email:
    - xoyip@piyox.info
