defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *defaults
  database: hatebuweb_development
  host: localhost

production:
  <<: *defaults
  database: hatebuweb_production

test:
  <<: *defaults
  database: hatebuweb_test
  host: localhost

  
